build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:buster
  amd64: ghcr.io/home-assistant/amd64-base-debian:buster
  armv7: ghcr.io/home-assistant/armv7-base-debian:buster
args:
  ALMOND_VERSION: v2.0.1
