version: 3.0.0-rc.1
slug: beta
name: Genie - Pre-release
description: The open-source, privacy-preserving voice assistant
url: https://github.com/stanford-oval/almond-hassio-repository/blob/master/beta
arch:
  - armv7
  - aarch64
  - amd64
audio: true
discovery:
  - almond
homeassistant: 0.102.0
homeassistant_api: true
image: stanfordoval/almond-hassio-addon-{arch}
ingress: true
init: false
panel_icon: mdi:comment-eye-outline
